import type { Incident, Severity } from './types'

export const dashboardTotals: Record<Severity | 'Unassigned', number> = {
  Critical: 4,
  High: 11,
  Medium: 23,
  Low: 8,
  Unassigned: 7,
}

export const incidents: Incident[] = [
  {
    id: 'INC-2026-0847', reference: 'CSIRT-4821', title: 'Legacy TLS 1.0 enabled on EC2 instance', severity: 'Critical', status: 'New', owner: 'Unassigned', source: 'Cloud Security CSIRT', sender: 'csirt-alerts@example.test', received: '7 Aug 2026 · 09:42 UTC', deadline: '23h 18m', account: 'Production (4820…3104)', region: 'eu-west-1', resource: 'i-012345', requestedAction: 'Disable TLS 1.0 and confirm that the service accepts TLS 1.2 or newer within 24 hours.', summary: 'CSIRT identified a public endpoint on an EC2 instance that still negotiates legacy TLS 1.0. The sender explicitly marked this alert Critical and requested remediation within 24 hours.', confidence: 98, indicators: ['TLSv1.0', 'i-012345', 'TCP/443'], related: ['INC-2026-0712 · Legacy cipher suite exposure'], conversationId: 'AAQkAGU4…93ca (redacted)',
    timeline: [
      { id: 'e1', actor: 'Outlook connector', action: 'Email received and validated', detail: 'Sender matched the approved CSIRT allowlist.', time: '09:42', tone: 'system' },
      { id: 'e2', actor: 'AI triage', action: 'Incident classified', detail: 'Explicit Critical severity preserved · confidence 98%.', time: '09:43', tone: 'ai' },
      { id: 'e3', actor: 'Notification service', action: 'Urgent alert delivered', detail: 'Posted to the Teams CSIRT on-call channel.', time: '09:43', tone: 'system' },
    ],
  },
  { id:'INC-2026-0842', reference:'CSIRT-4818', title:'Suspected IAM access key compromise', severity:'Critical', status:'Investigating', owner:'Alex Morgan', source:'AWS Security Operations', sender:'aws-security@example.test', received:'7 Aug 2026 · 09:18 UTC', deadline:'3h 42m', account:'Production (4820…3104)', region:'us-east-1', resource:'iam:user/prod-deploy', requestedAction:'Disable the exposed access key and confirm CloudTrail review.', summary:'A deployment key appeared in a public code sample. API activity from an unfamiliar network followed the disclosure.', confidence:96, indicators:['AKIA…7Q2 (redacted)','185.220.101.42'], related:[], conversationId:'AAQkAGQ1…8b10 (redacted)', timeline:[{id:'e1',actor:'Alex Morgan',action:'Investigation started',detail:'CloudTrail query RUN-391 attached.',time:'09:26',tone:'person'}] },
  { id:'INC-2026-0839', reference:'CSIRT-4811', title:'GuardDuty cryptocurrency activity', severity:'High', status:'Acknowledged', owner:'Maya Chen', source:'Cloud Security CSIRT', sender:'cloud-csirt@example.test', received:'7 Aug 2026 · 08:51 UTC', deadline:'7h 09m', account:'Digital (7719…2081)', region:'eu-west-1', resource:'i-0a814cf3e3b98d721', requestedAction:'Isolate the instance and preserve volatile evidence.', summary:'GuardDuty detected DNS requests associated with cryptocurrency mining. Persistence is not yet confirmed.', confidence:91, indicators:['pool.supportxmr.com','Unusual DNS volume'], related:[], conversationId:'AAQkAGQ2…445c (redacted)', timeline:[{id:'e1',actor:'Maya Chen',action:'Incident acknowledged',detail:'Owner assigned.',time:'09:04',tone:'person'}] },
  { id:'INC-2026-0835', reference:'SOC-9924', title:'Unusual S3 bulk download', severity:'High', status:'Investigating', owner:'Jordan Lee', source:'Data Protection Team', sender:'soc@example.test', received:'7 Aug 2026 · 08:05 UTC', deadline:'11h 55m', account:'Finance (1934…0029)', region:'us-east-1', resource:'s3://finance-reporting-prod', requestedAction:'Validate the download with the data owner.', summary:'A federated analyst role downloaded 8.4 GB across 2,100 objects outside normal hours.', confidence:84, indicators:['FinanceAnalyst','2,100 GetObject calls'], related:[], conversationId:'AAQkAGQ8…991a (redacted)', timeline:[{id:'e1',actor:'Jordan Lee',action:'Data owner contacted',detail:'Awaiting confirmation.',time:'08:24',tone:'person'}] },
  { id:'INC-2026-0828', reference:'CSPM-1845', title:'Public security group exposure', severity:'Medium', status:'New', owner:'Unassigned', source:'Cloud Posture Team', sender:'posture@example.test', received:'7 Aug 2026 · 06:44 UTC', deadline:'2d 5h', account:'Sandbox (5542…3188)', region:'us-east-1', resource:'sg-0816de45794b3c210', requestedAction:'Confirm business justification for public SSH.', summary:'A security group permits inbound SSH from the internet. No successful connections appear in sampled telemetry.', confidence:89, indicators:['0.0.0.0/0:22'], related:[], conversationId:'AAQkAGQ3…0d27 (redacted)', timeline:[{id:'e1',actor:'Automation',action:'Incident created',detail:'No urgent notification required.',time:'06:45',tone:'system'}] },
  { id:'INC-2026-0817', reference:'ID-3342', title:'Repeated Cognito login failures', severity:'Low', status:'Awaiting approval', owner:'Alex Rivera', source:'Identity Operations', sender:'identity@example.test', received:'6 Aug 2026 · 15:21 UTC', deadline:'4d 2h', account:'Shared services (8810…4822)', region:'us-east-1', resource:'Cognito pool us-east-1_Vp93Az', requestedAction:'Notify the user and monitor for successful access.', summary:'A user received 46 failed authentication attempts. MFA prevented account access.', confidence:78, indicators:['46 failed attempts','MFA enforced'], related:[], conversationId:'AAQkAGQ7…291b (redacted)', timeline:[{id:'e1',actor:'Alex Rivera',action:'Approval requested',detail:'Draft response ready for review.',time:'16:08',tone:'person'}] },
]
